-- Política de Privacidad (Ley 25.326) editable desde /admin, + contacto de
-- Telegram para recibir comprobantes de transferencia (se muestra junto a
-- mail y WhatsApp, uno por cada dato que esté cargado). Segura de correr en
-- un proyecto existente.

alter table site_settings add column if not exists privacy_heading text not null default
  'Política de Privacidad';

alter table site_settings add column if not exists privacy_content text not null default '';

alter table site_settings add column if not exists transfer_telegram_contact text not null default '';

-- Si ya habías corrido una versión anterior de esta migración con la
-- columna transfer_proof_channel (canal único a elegir), se descarta: ahora
-- se muestran todos los canales configurados, no uno solo.
alter table site_settings drop column if exists transfer_proof_channel;

update site_settings set privacy_content =
  'Última actualización: 2026.

Esta Política de Privacidad describe cómo nmtech solutions ("nosotros", "el sitio") recolecta, usa, conserva y protege los datos personales de quienes visitan este sitio, completan el formulario de captura de leads, o compran alguno de nuestros ebooks. Se aplica en conjunto con nuestros Términos y Condiciones, y se rige por la Ley N° 25.326 de Protección de Datos Personales de la República Argentina y su normativa complementaria.

1. RESPONSABLE DEL TRATAMIENTO. El responsable del tratamiento de los datos personales recolectados a través de este sitio es nmtech solutions. Podés contactarnos por cualquier consulta relacionada con tus datos personales a través de los medios indicados en la sección "Contacto" del sitio y en el punto 12 de esta Política.

2. QUÉ DATOS RECOLECTAMOS. 2.1. Datos que nos das directamente: cuando completás el formulario de un ebook, recolectamos tu nombre, dirección de mail, la temática de interés que elegís, y (si querés) un comentario adicional o un código de descuento. Si nos escribís por mail, WhatsApp o Telegram para enviarnos un comprobante de transferencia, recolectamos los datos que decidas compartirnos en esa comunicación (por ejemplo, tu número de teléfono si nos escribís por WhatsApp). 2.2. Datos que se recolectan automáticamente: cuando navegás el sitio, se registran automáticamente datos técnicos como tu dirección IP, tipo de dispositivo y navegador, páginas visitadas y, si aceptaste el banner de cookies, identificadores de seguimiento generados por el Píxel de Meta (ver punto 7). 2.3. No recolectamos datos sensibles (en el sentido del art. 2 de la Ley 25.326, como origen racial, opiniones políticas, salud, etc.) ni datos de tarjetas de crédito, cuentas bancarias de terceros o comprobantes de pago: esos datos, si los compartís para acreditar una transferencia, quedan en el canal de mensajería que uses (mail, WhatsApp o Telegram) y no se almacenan en la base de datos del sitio.

3. PARA QUÉ USAMOS TUS DATOS (FINALIDAD). Usamos los datos que recolectamos para: (a) entregarte el primer capítulo gratis del ebook que elegiste; (b) gestionar tu compra y confirmarte el pago (por Hotmart, Tienda Nube o transferencia); (c) enviarte el ebook completo por mail una vez confirmado el pago; (d) responder tus consultas y darte seguimiento comercial; (e) si aceptaste el banner de cookies, medir la efectividad de nuestras campañas de publicidad en Meta (Facebook/Instagram) y mostrarte anuncios relevantes de nuestros propios productos (remarketing); (f) cumplir obligaciones legales, contables o fiscales que puedan corresponder. No usamos tus datos para fines distintos a los aquí descriptos, ni los usamos para tomar decisiones automatizadas que produzcan efectos jurídicos sobre vos.

4. BASE LEGAL DEL TRATAMIENTO. El tratamiento de tus datos se basa en tu consentimiento libre, expreso e informado, que nos das: (a) al completar y enviar el formulario del sitio, para los datos de contacto y la gestión de tu solicitud/compra; y (b) al aceptar el banner de cookies, específicamente para la activación del Píxel de Meta y el tratamiento de datos con fines de marketing. Si no aceptás el banner de cookies, el Píxel de Meta no se activa y no se recolecta ningún dato con fines publicitarios; podés igualmente leer el capítulo gratis y comprar cualquier ebook con total normalidad.

5. PLAZO DE CONSERVACIÓN. Conservamos tus datos personales mientras sea necesario para las finalidades descriptas en el punto 3, y en todo caso mientras exista una relación comercial o de consulta activa con vos, más los plazos adicionales que puedan exigir normas legales, contables o fiscales aplicables (por ejemplo, comprobantes de venta). Podés solicitar la supresión de tus datos antes de ese plazo escribiéndonos por los medios de contacto indicados, salvo que exista una obligación legal que nos impida eliminarlos antes.

6. A QUIÉNES SE COMUNICAN TUS DATOS (DESTINATARIOS Y TRANSFERENCIA INTERNACIONAL). Para poder ofrecer este servicio, compartimos una parte de tus datos con los siguientes proveedores, que actúan como encargados del tratamiento o, en el caso de Hotmart y Tienda Nube, como responsables independientes de la etapa de pago:
  • Supabase Inc.: aloja la base de datos donde se guardan los leads y los ebooks (infraestructura en la nube, con sede fuera de la Argentina).
  • Google LLC (Gmail): se usa para enviar los mails automáticos del sitio (capítulo gratis, confirmación de compra).
  • Vercel Inc.: aloja y sirve el sitio web (hosting).
  • Meta Platforms, Inc. (Facebook/Instagram): si aceptaste el banner de cookies, recibe datos de navegación y, de forma encriptada/anonimizada (hasheada), tu mail, con el único fin de medir conversiones de nuestras campañas publicitarias y mostrarte anuncios relevantes. Meta actúa como responsable independiente respecto del uso que le da a esos datos dentro de su propia plataforma, conforme a su propia política de privacidad (https://www.facebook.com/privacy/policy/).
  • Hotmart y Tienda Nube: si elegís comprar por alguno de estos medios, el proceso de pago se realiza íntegramente en sus plataformas, que recolectan y procesan tus datos de pago bajo sus propias políticas de privacidad, ajenas a nosotros.
Estos proveedores pueden estar ubicados fuera de la República Argentina, por lo que tus datos pueden ser objeto de una transferencia internacional. En esos casos, procuramos utilizar proveedores que ofrezcan garantías adecuadas de protección de datos conforme a los estándares exigidos por el art. 12 de la Ley 25.326, y solo compartimos los datos estrictamente necesarios para cada finalidad. No vendemos tus datos personales a terceros bajo ninguna circunstancia.

7. COOKIES Y TECNOLOGÍAS DE SEGUIMIENTO. 7.1. ¿Qué es el Píxel de Meta? Es un fragmento de código de Facebook/Instagram (Meta) que, cuando está activo, permite registrar acciones que realizás en el sitio (como visitar una página o hacer clic en un botón de compra) para medir la efectividad de nuestras campañas publicitarias y mostrarte anuncios más relevantes en esas plataformas. 7.2. Consentimiento: al ingresar al sitio, te mostramos un banner donde podés Aceptar o Rechazar el uso de estas cookies/tecnologías de seguimiento no esenciales. Tu elección se guarda en tu propio navegador (localStorage) y el Píxel de Meta solo se activa si elegís "Aceptar". 7.3. Si rechazás: el sitio funciona exactamente igual, podés leer el capítulo gratis y comprar cualquier ebook por cualquiera de los tres medios disponibles; simplemente no se activa el seguimiento de Meta ni se comparte información con fines publicitarios. 7.4. Podés cambiar tu elección en cualquier momento borrando los datos de navegación (localStorage) de tu navegador para este sitio, lo que va a hacer que el banner vuelva a aparecer en tu próxima visita. 7.5. Este sitio no utiliza cookies propias de seguimiento para visitantes; la única cookie técnica que usamos es la sesión de inicio de sesión del panel administrativo interno, que no te afecta como visitante o comprador.

8. TUS DERECHOS SOBRE TUS DATOS PERSONALES. De acuerdo con los arts. 14, 16 y 20 de la Ley 25.326, tenés derecho a: (a) ACCESO: solicitar confirmación de si tratamos datos tuyos y acceder a ellos; (b) RECTIFICACIÓN/ACTUALIZACIÓN: pedir que corrijamos datos inexactos o desactualizados; (c) SUPRESIÓN/CANCELACIÓN: pedir que eliminemos tus datos cuando corresponda; (d) OPOSICIÓN: oponerte al tratamiento de tus datos con fines de marketing en cualquier momento. Estos derechos son gratuitos y podés ejercerlos escribiéndonos por los medios de contacto indicados en el punto 12, acreditando tu identidad. Vamos a responder tu solicitud dentro de los plazos que establece la normativa vigente. Además, si considerás que no dimos cumplimiento adecuado a tus derechos, tenés derecho a presentar una denuncia o reclamo ante la Agencia de Acceso a la Información Pública (AAIP), órgano de control de la Ley 25.326 en la República Argentina (www.argentina.gob.ar/aaip), que es la Autoridad de Aplicación de la Ley N° 25.326 y tiene la atribución de atender reclamos vinculados al incumplimiento de las normas sobre protección de datos personales.

9. SEGURIDAD DE LOS DATOS. Adoptamos medidas técnicas y organizativas razonables para proteger tus datos personales contra pérdida, uso indebido, acceso no autorizado, alteración o divulgación, entre ellas: acceso restringido y protegido por usuario/contraseña al panel administrativo, comunicación cifrada (HTTPS) en todo el sitio, y uso de proveedores de infraestructura reconocidos (Supabase, Vercel). Ningún sistema es 100% infalible, pero trabajamos para mantener estándares razonables de seguridad acordes al tamaño y naturaleza de este proyecto.

10. MENORES DE EDAD. Este sitio y sus productos están dirigidos a personas mayores de 18 años. No recolectamos deliberadamente datos personales de menores de edad. Si tomamos conocimiento de que se recolectaron datos de un menor sin el consentimiento correspondiente de sus padres o tutores, vamos a eliminarlos.

11. MODIFICACIONES A ESTA POLÍTICA. Podemos modificar esta Política de Privacidad en cualquier momento, por ejemplo ante cambios normativos o en las herramientas que usamos. La versión vigente es siempre la publicada en esta misma página, con su fecha de última actualización. Te recomendamos revisarla periódicamente.

12. CONTACTO. Para ejercer tus derechos o realizar cualquier consulta sobre esta Política de Privacidad o el tratamiento de tus datos, podés escribirnos por los medios de contacto indicados en la sección "Contacto" de este sitio.

NOTA: esta Política fue redactada con el mayor rigor posible para cubrir los requisitos de la Ley 25.326, pero no reemplaza el asesoramiento de un abogado especializado en protección de datos, especialmente si el negocio crece o cambia su forma de operar.'
where id = 1 and privacy_content = '';
